'use strict';

module.exports = {
    OP_PAYMENT_NOT_APPROVED: 'OP_PAYMENT_NOT_APPROVED',
    OP_GW_RULE_ERROR: 'OP_GW_RULE_ERROR',
    OP_PAYMENT_EXCEED_AMOUNT: 'OP_PAYMENT_EXCEED_AMOUNT',
    OP_PAYMENT_NOT_APPROVED: 'OP_PAYMENT_NOT_COMPLETED',
    OP_REFUND_COMPLETED: 'OP_REFUND_COMPLETED'
};
