'use strict';

module.exports = {
    OP_FIELD_REQUIRED: 'OP_FIELD_REQUIRED',
    OP_FIELD_INVALID_EMAIL: 'OP_FIELD_INVALID_EMAIL',
    OP_FIELD_INVALID_URL: 'OP_FIELD_INVALID_URL',
    OP_FIELD_EMPTY: 'OP_FIELD_EMPTY',
    OP_FIELD_INVALID_INPUT: 'OP_FIELD_INVALID_INPUT',
    OP_FIELD_INVALID_TYPE: 'OP_FIELD_INVALID_TYPE',
    OP_FIELD_MAX_LENGTH: 'OP_FIELD_MAX_LENGTH',
    OP_FIELD_NOT_ALLOWED: 'OP_FIELD_NOT_ALLOWED',
    OP_FIELD_ERROR_UNKNOWN: 'OP_FIELD_ERROR_UNKNOWN',
    OP_FIELD_INVALID_VALUE: 'OP_FIELD_INVALID_VALUE',
    OP_INVALID_ACTION: 'OP_INVALID_ACTION',
    OP_ERR_SERVER_TIMEOUT: 'OP_ERR_SERVER_TIMEOUT',
    OP_ERR_INTERNAL_SERVER: 'OP_ERR_INTERNAL_SERVER',
    OP_INVALID_TOKEN: 'OP_INVALID_TOKEN',
    OP_INVALID_MERCHANT: 'OP_INVALID_MERCHANT'
};
